services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-produits
    environment:
      POSTGRES_DB: produitsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  produits-service:
    build: ./produits-service
    container_name: produits-service
    ports:
      - "8091:8091"
    depends_on:
      - postgres
      - redis
      - eureka-server

  avis-service:
    build: ./avis-service
    container_name: avis-service
    ports:
      - "8092:8092"
    depends_on:
      - postgres
      - eureka-server

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - produits-service
      - avis-service